name:                advent-of-code
version:             0.1.0.0
github:              "erochest/advent-of-code"
license:             BSD3
author:              "Eric Rochester"
maintainer:          "erochest@gmail.com"
copyright:           "Eric Rochester"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Play

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/erochest/day1#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec
- bytestring
- containers
- vector

library:
  source-dirs: src

executables:
  advent2018-01:
    main:                Main.hs
    source-dirs:         app/advent2018_01
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    # - day1
    - bytestring
    - unordered-containers
  advent2018-02:
    main:                Main.hs
    source-dirs:         app/advent2018_02
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - unordered-containers
    - hashable
  advent2018-03:
    main:                Main.hs
    source-dirs:         app/advent2018_03
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - attoparsec
    - bytestring
    - unordered-containers
  advent2018-04:
    main:                Main.hs
    source-dirs:         app/advent2018_04
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code
    - attoparsec
    - attoparsec-time
    - bytestring
    - hashable
    - time
    - unordered-containers
  advent2018-05:
    main:                Main.hs
    source-dirs:         app/advent2018_05
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code
    - bytestring
    - unordered-containers
  advent2021-01:
    dependencies:
    - advent-of-code
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: app/advent2021_01
  advent2021-02:
    dependencies:
    - advent-of-code
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: app/advent2021_02
  advent2021-03:
    dependencies:
    - advent-of-code
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: app/advent2021_03
  advent2021-04:
    dependencies:
    - advent-of-code
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: app/advent2021_04
  advent2021-05:
    dependencies:
    - advent-of-code
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: app/advent2021_05
  advent2021-06:
    dependencies: &id001
    - advent-of-code
    ghc-options: &id002
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: app/advent2021_06

tests:
  day2021_02-test:
    main: Spec.hs
    source-dirs: test/day2021_02
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code
    - tasty
    - tasty-hunit
  adent2021_03-test:
    dependencies:
    - advent-of-code
    - tasty
    - tasty-hunit
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    main: Spec.hs
    source-dirs: test/day2021_03
  advent2021_04-test:
    dependencies:
    - advent-of-code
    - tasty
    - tasty-hunit
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    main: Spec.hs
    source-dirs: test/day2021_04
  advent2021_05-test:
    dependencies:
    - advent-of-code
    - tasty
    - tasty-hunit
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    main: Spec.hs
    source-dirs: test/day2021_05
  advent2021_06-test:
    dependencies: &id003
    - advent-of-code
    - tasty
    - tasty-hunit
    ghc-options: &id004
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    main: Spec.hs
    source-dirs: test/day2021_06
