author: Eric Rochester
copyright: '2021'
dependencies:
- base >= 4.7 && < 5
- attoparsec
- bytestring
- containers
- parallel
- vector
description: Please see the README on GitHub at <https://github.com/erochest/day2#readme>
executables:
  day7-exe:
    dependencies: *id001
    ghc-options: *id002
    main: Main.hs
    source-dirs: app/day7
extra-source-files:
- README.md
- ChangeLog.md
github: erochest/advent-2021
library:
  source-dirs: src
license: BSD3
maintainer: erochest@gmail.com
name: Advent2021
version: 0.1.0.0
