set dotenv-load := true

year := datetime("%Y")
day := datetime("%d")

test:
    uv run python -m pytest

run part="1" day=datetime("%d") year=datetime("%Y"):
    uv run python -c 'from aoc.y2025.day{{day}} import part{{part}}; from aoc.io import read_data_file; print(part{{part}}(read_data_file({{year}}, {{trim_start_match(day, "0")}})))'

download day=datetime("%d") year=datetime("%Y"):
    aoc download --input-only --input-file ../data/{{year}}/day{{day}}.data


submit part value day=datetime("%d") year=datetime("%Y"):
    aoc submit --year={{year}} --day={{day}} {{part}} {{value}}

date day=datetime("%d") year=datetime("%Y"):
    echo "today is {{day}} of {{year}}"
