
set dotenv-load := true

year := datetime("%Y")
day := datetime("%d")

default: test run

test day=datetime("%d") year=datetime("%Y"):
    tardi ./aoc/y{{year}}/d{{day}}-test.tardi --print-stack

run day=datetime("%d") year=datetime("%Y"):
    tardi ./aoc/y{{year}}/d{{day}}.tardi


download day=datetime("%d") year=datetime("%Y"):
    aoc download --input-only --input-file ../data/{{year}}/day{{day}}.data


submit part value day=datetime("%d") year=datetime("%Y"):
    aoc submit --year={{year}} --day={{day}} {{part}} {{value}}

date day=datetime("%d") year=datetime("%Y"):
    echo "today is {{day}} of {{year}}"
