
day{{ year }}_{{ day }}:
	gforth s/{{ year }}/day{{ day }}.fth t/{{ year }}/test-day{{ day }}.fth -e '$(TEST_WORD)' -e bye
	gforth s/{{ year }}/day{{ day }}.fth -e parta -e bye
	gforth s/{{ year }}/day{{ day }}.fth -e partb -e bye

.PHONY: day{{ year }}_{{ day }}